--INSERT INTO enderecos(pessoa_id, logradouro, cep, numero, cidade) VALUES (1, 'Rua Pereira Gustão', 12, 123, 'Fortaleza' );
--INSERT INTO enderecos(pessoa_id,logradouro, cep, numero, cidade) VALUES (2, 'Rua Felipe', 15, 34, 'Maracanaú' );
--INSERT INTO enderecos(pessoa_id, logradouro, cep, numero, cidade) VALUES (3, 'Rua Felizardo', 75, 675, 'Mucuripe' );
--INSERT INTO enderecos(pessoa_id, logradouro, cep, numero, cidade) VALUES (4,'Rua Fel', 485, 947, 'Pacatuba' );
--

--INSERT INTO enderecos(id_endereco_pessoa, logradouro, cep, numero, cidade) VALUES (1, 'Rua Pereira Gustão', 12, 123, 'Fortaleza' );
--INSERT INTO enderecos(id_endereco_pessoa, logradouro, cep, numero, cidade) VALUES (2,'Rua Felipe', 15, 34, 'Maracanaú' );
--INSERT INTO enderecos(id_endereco_pessoa, logradouro, cep, numero, cidade) VALUES (3, 'Rua Felizardo', 75, 675, 'Mucuripe' );
--INSERT INTO enderecos(id_endereco_pessoa, logradouro, cep, numero, cidade) VALUES (4, 'Rua Fel', 485, 947, 'Pacatuba' );
----
----
----
----
----
----
--INSERT INTO pessoas(id_endereco, nome, data_de_nascimento) VALUES (1, 'Maria', '1990-01-21');
--INSERT INTO pessoas(id_endereco, nome, data_de_nascimento) VALUES (2, 'Bob', '2000-12-08');
--INSERT INTO pessoas(id_endereco, nome, data_de_nascimento) VALUES (3, 'Alex', '1995-06-02');
--INSERT INTO pessoas(id_endereco, nome, data_de_nascimento) VALUES (4, 'Ana', '1990-01-21');